language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email:
    recipients:
      - 958501820@qq.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - cd _book
  - git init
  - git remote add origin https://${GH_REF}
  - git add .
  - git commit -m "Updated By Travis-CI With Build  For Github Pages"
  - git push --force --quiet "https://${TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
  global:
    - GH_REF=github.com/lixindong/book.git # 设置 github 地址
